site_name: AllFunds Wiki
site_url: https://prasadkothapally.github.io/wiki/
repo_url: https://github.com/prasadkothapally/wiki.git
edit_uri: https://gitlabnew.techwave.net/fintrust/wiki/-/edit/main/docs/

nav:
  - Home: index.md
  - About: about.md

#theme: readthedocs
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences
plugins:
 - kroki:
    ServerURL: https://kroki.io
    FencePrefix: kroki-
    enable_plantuml: true
    EnableBlockDiag: True
    Enablebpmn: True
    EnableMermaid: False
    EnableDiagramsnet: True
    FileTypes:
      - png
      - svg
 - plantuml:
    puml_url: https://www.plantuml.com/plantuml/
    num_workers: 8
 - mermaid2:
 - print-site:
